version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: llm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: llm_observability
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: shaikvali03/llm-observability-backend:latest
    container_name: llm_backend
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    image: shaikvali03/llm-observability-frontend:latest
    container_name: llm_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3001:3000"

  prometheus:
    image: prom/prometheus
    container_name: llm_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: llm_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: llm_jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

volumes:
  postgres_data:
  grafana_data: